// Generated by gencpp from file object_handling/example.msg
// DO NOT EDIT!


#ifndef OBJECT_HANDLING_MESSAGE_EXAMPLE_H
#define OBJECT_HANDLING_MESSAGE_EXAMPLE_H

#include <ros/service_traits.h>


#include <object_handling/exampleRequest.h>
#include <object_handling/exampleResponse.h>


namespace object_handling
{

struct example
{

typedef exampleRequest Request;
typedef exampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct example
} // namespace object_handling


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_handling::example > {
  static const char* value()
  {
    return "978efc3b4d217b6a9fca06d03983e5b2";
  }

  static const char* value(const ::object_handling::example&) { return value(); }
};

template<>
struct DataType< ::object_handling::example > {
  static const char* value()
  {
    return "object_handling/example";
  }

  static const char* value(const ::object_handling::example&) { return value(); }
};


// service_traits::MD5Sum< ::object_handling::exampleRequest> should match
// service_traits::MD5Sum< ::object_handling::example >
template<>
struct MD5Sum< ::object_handling::exampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_handling::example >::value();
  }
  static const char* value(const ::object_handling::exampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_handling::exampleRequest> should match
// service_traits::DataType< ::object_handling::example >
template<>
struct DataType< ::object_handling::exampleRequest>
{
  static const char* value()
  {
    return DataType< ::object_handling::example >::value();
  }
  static const char* value(const ::object_handling::exampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_handling::exampleResponse> should match
// service_traits::MD5Sum< ::object_handling::example >
template<>
struct MD5Sum< ::object_handling::exampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_handling::example >::value();
  }
  static const char* value(const ::object_handling::exampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_handling::exampleResponse> should match
// service_traits::DataType< ::object_handling::example >
template<>
struct DataType< ::object_handling::exampleResponse>
{
  static const char* value()
  {
    return DataType< ::object_handling::example >::value();
  }
  static const char* value(const ::object_handling::exampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_HANDLING_MESSAGE_EXAMPLE_H
