// Generated by gencpp from file panda_world_spawner/Task2Service.msg
// DO NOT EDIT!


#ifndef PANDA_WORLD_SPAWNER_MESSAGE_TASK2SERVICE_H
#define PANDA_WORLD_SPAWNER_MESSAGE_TASK2SERVICE_H

#include <ros/service_traits.h>


#include <panda_world_spawner/Task2ServiceRequest.h>
#include <panda_world_spawner/Task2ServiceResponse.h>


namespace panda_world_spawner
{

struct Task2Service
{

typedef Task2ServiceRequest Request;
typedef Task2ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task2Service
} // namespace panda_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_world_spawner::Task2Service > {
  static const char* value()
  {
    return "a7aedf2afa2ac40fff84a9dc873ab94d";
  }

  static const char* value(const ::panda_world_spawner::Task2Service&) { return value(); }
};

template<>
struct DataType< ::panda_world_spawner::Task2Service > {
  static const char* value()
  {
    return "panda_world_spawner/Task2Service";
  }

  static const char* value(const ::panda_world_spawner::Task2Service&) { return value(); }
};


// service_traits::MD5Sum< ::panda_world_spawner::Task2ServiceRequest> should match
// service_traits::MD5Sum< ::panda_world_spawner::Task2Service >
template<>
struct MD5Sum< ::panda_world_spawner::Task2ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task2ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_world_spawner::Task2ServiceRequest> should match
// service_traits::DataType< ::panda_world_spawner::Task2Service >
template<>
struct DataType< ::panda_world_spawner::Task2ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task2ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_world_spawner::Task2ServiceResponse> should match
// service_traits::MD5Sum< ::panda_world_spawner::Task2Service >
template<>
struct MD5Sum< ::panda_world_spawner::Task2ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task2ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_world_spawner::Task2ServiceResponse> should match
// service_traits::DataType< ::panda_world_spawner::Task2Service >
template<>
struct DataType< ::panda_world_spawner::Task2ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_world_spawner::Task2Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task2ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_WORLD_SPAWNER_MESSAGE_TASK2SERVICE_H
