// Generated by gencpp from file panda_world_spawner/Task3Service.msg
// DO NOT EDIT!


#ifndef PANDA_WORLD_SPAWNER_MESSAGE_TASK3SERVICE_H
#define PANDA_WORLD_SPAWNER_MESSAGE_TASK3SERVICE_H

#include <ros/service_traits.h>


#include <panda_world_spawner/Task3ServiceRequest.h>
#include <panda_world_spawner/Task3ServiceResponse.h>


namespace panda_world_spawner
{

struct Task3Service
{

typedef Task3ServiceRequest Request;
typedef Task3ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task3Service
} // namespace panda_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_world_spawner::Task3Service > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::panda_world_spawner::Task3Service&) { return value(); }
};

template<>
struct DataType< ::panda_world_spawner::Task3Service > {
  static const char* value()
  {
    return "panda_world_spawner/Task3Service";
  }

  static const char* value(const ::panda_world_spawner::Task3Service&) { return value(); }
};


// service_traits::MD5Sum< ::panda_world_spawner::Task3ServiceRequest> should match
// service_traits::MD5Sum< ::panda_world_spawner::Task3Service >
template<>
struct MD5Sum< ::panda_world_spawner::Task3ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task3ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_world_spawner::Task3ServiceRequest> should match
// service_traits::DataType< ::panda_world_spawner::Task3Service >
template<>
struct DataType< ::panda_world_spawner::Task3ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::panda_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task3ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_world_spawner::Task3ServiceResponse> should match
// service_traits::MD5Sum< ::panda_world_spawner::Task3Service >
template<>
struct MD5Sum< ::panda_world_spawner::Task3ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task3ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_world_spawner::Task3ServiceResponse> should match
// service_traits::DataType< ::panda_world_spawner::Task3Service >
template<>
struct DataType< ::panda_world_spawner::Task3ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::panda_world_spawner::Task3Service >::value();
  }
  static const char* value(const ::panda_world_spawner::Task3ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_WORLD_SPAWNER_MESSAGE_TASK3SERVICE_H
